# Generated by Django 3.1.1 on 2020-09-14 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("leaveapp", "0001_initial")]

    operations = [
        migrations.AddField(
            model_name="leave",
            name="leave_type",
            field=models.CharField(
                choices=[
                    ("first_half", "First Half"),
                    ("second_half", "Second Half"),
                    ("full_day", "Full Day"),
                ],
                default="first_half",
                max_length=15,
            ),
        ),
        migrations.AlterField(
            model_name="leave",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("accepted", "Accepted"),
                    ("rejected", "Rejected"),
                ],
                default="pending",
                max_length=15,
            ),
        ),
    ]
