# Generated by Django 3.1.1 on 2020-09-14 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("leaveapp", "0002_auto_20200914_0750")]

    operations = [
        migrations.AlterField(
            model_name="leave", name="created_at", field=models.DateField(null=True)
        )
    ]
