# Generated by Django 3.1.1 on 2020-09-14 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("leaveapp", "0003_auto_20200914_0940"),
    ]

    operations = [
        migrations.AlterField(
            model_name="leave",
            name="created_at",
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
