# Generated by Django 3.1.1 on 2020-09-21 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("leaveapp", "0006_auto_20200918_0830"),
    ]

    operations = [
        migrations.CreateModel(
            name="Task",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=250)),
                ("description", models.TextField()),
                ("created_at", models.DateField(auto_now_add=True, null=True)),
                ("updated_at", models.DateField(null=True)),
                ("user_name", models.CharField(max_length=50)),
                ("estimated_hour", models.FloatField()),
                ("channel_id", models.CharField(default="", max_length=150)),
            ],
            options={
                "db_table": "task",
            },
        ),
    ]
