# Generated by Django 3.1.1 on 2020-09-21 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("leaveapp", "0007_task"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="leave",
            name="channel_id",
        ),
        migrations.AddField(
            model_name="leave",
            name="response_url",
            field=models.URLField(default="", max_length=150),
        ),
    ]
